### ISSUE TITLE
Unable to create mod file

### ISSUE THREAD

**Issue by philba** [MetaIdea/NMS_AUTO_MOD_BUILDER_AND_UPDATER_SCRIPT_SYSTEM#1]
Decided to test a simple mod to make sure I understood the process. I created a folder called 'ModScript' in the folder containing the BuildMod.bat file and copied the 'JetpackWalkSwimSpeed.lua' file into that folder. Running BuildMod.bat looks like to found the .lua file and appears to run. However, it appears that the '..\Builds\JetpackWalkSwimSpeed.pak' file was never created. I don't see any errors from psarc.exe, so I'm not sure what is happening there. The output of the run is attached below... 

[BatchFileOutput.txt](https://github.com/MetaIdea/nms-auto-modbuilder-updater-modscript-system/files/3038981/BatchFileOutput.txt)

**Comment by HolterPhylo** [comment]
Please goto:  https://www.nexusmods.com/nomanssky/mods/957 and download 1.35W and try the JetpackWalkSwimSpeed.lua script in ModScriptCollection folder.  That should do the trick.  1.35W is much more uptodate.  The code in this GitHub is outdated.  Regards, Wbertro aka TheBossBoy
